UPSTREAM: ksm05: Fix build warning/error with -Wnull-dereference
Using the Android clang build, which uses -Werror -Wnull-dereference,
the following error is seen:

testcases/kernel/mem/ksm/ksm05.c:81:3: error: indirection of
non-volatile null pointer will be deleted, not trap
[-Werror,-Wnull-dereference]
  *(char *)NULL = 0;      /* SIGSEGV occurs as expected. */
  ^~~~~~~~~~~~~
testcases/kernel/mem/ksm/ksm05.c:81:3: note: consider using
__builtin_trap() or qualifying pointer with 'volatile'
1 error generated.

Change it to "volatile char *" which avoids this build issue, without
negatively affecting the test.

Signed-off-by: Alistair Strachan <astrachan@google.com>
Signed-off-by: Petr Vorel <pvorel@suse.cz>
(cherry picked from commit 058b2e55825344ab9da0567f94ef535749041ac9)
Change-Id: I8d4154144bd61c1b617b7bf88ff9a2975a6392f3
Signed-off-by: Alistair Strachan <astrachan@google.com>